SELECT FIRSTNAME, MARKS,
CASE
WHEN MARKS >= 90 THEN 'A'
WHEN MARKS >= 75 THEN 'B'
WHEN MARKS >= 60 THEN 'C'
ELSE 'D'
END AS GRADE
FROM STUDENTS;

SELECT NAME, SALARY,
CASE
WHEN SALARY >= 70000 THEN 'HIGHSALARY'
WHEN SALARY >= 50000 THEN 'MEDIUMSALARY'
ELSE 'LOW'
END AS SALARYBAND
FROM EMPLOYEES;