CREATE PROCEDURE GETORDERSBYPRODUCT
    @PRODUCTID INT
AS
BEGIN
    SELECT
	O.ORDERID,
	O.QUANTITY,
	O.ORDERDATE,
	P.PRODUCTNAME,
	P.PRICE
FROM ORDERS O
INNER JOIN PRODUCTS P ON O.PRODUCTID = P.PRODUCTID
WHERE O.PRODUCTID = @PRODUCTID;
END;