CREATE PROCEDURE GETPRODUCTREVENUE
    @PRODUCTID INT
AS
BEGIN
SELECT 
O.QUANTITY,
P.PRICE,
(O.QUANTITY * P.PRICE) AS TOTALREVENUE
FROM ORDERS O
INNER JOIN PRODUCTS P ON O.PRODUCTID = P.PRODUCTID
WHERE O.PRODUCTID = @PRODUCTID;
END;


