SELECT FIRSTNAME, DATEDIFF(YEAR, DOB, GETDATE()) AS AGE FROM STUDENTS;

select NAME, ROUND(SALARY, -3) AS ROUNDEDSALARY FROM EMPLOYEES;

SELECT FIRSTNAME, LOWER(FIRSTNAME) AS LOWERCASENAME FROM STUDENTS;