CREATE TABLE BOOKS(
BOOKID INT PRIMARY KEY,
TITLTE VARCHAR(50),
AUTHOR VARCHAR(50),
GENRE VARCHAR(50),
PRICE DECIMAL(8,2),
PUBLISHEDYEAR INT

);

INSERT INTO BOOKS(BOOKID, TITLE, AUTHOR, GENRE, PRICE, PUBLISHEDYEAR)
VALUES
(1, 'ATOMIC HABITS', 'JAMES CLEAR', 'SELF-HELP', 499.00, 2018),
(2, 'THE ALCHEMIST', 'PAULO COELHO', 'FICTION', 299.00, 1993),
(3, 'CLEAN CODE', 'ROBERT C.MARTIN', 'PROGRAMMING', 799.00, 2008),
(4, 'SAPIENS', 'YUVAL NAOH HARARI', 'HISTORY', 599.00, 20215);

SELECT * FROM BOOKS;

UPDATE BOOKS SET GENRE = 'HORROR' WHERE GENRE = 'PROGRAMMING';

DELETE BOOKS WHERE PUBLISHEDYEAR = 1993;