CREATE TABLE PRODUCTS(
PRODUCTID INT PRIMARY KEY,
PRODUCTNAME VARCHAR(50),
PRICE DECIMAL(10,2) );

CREATE TABLE ORDERS(
ORDERID INT PRIMARY KEY,
PRODUCTID INT,
QUANTITY INT,
ORDERDATE DATE,
FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID)
);
