SELECT  
ORDERS.ORDERID,
PRODUCTS.PRODUCTID,
ORDERS.QUANTITY,
PRODUCTS.PRICE,
(ORDERS.QUANTITY * PRODUCTS.PRICE) AS TOTALAMOUNT,
ORDERS.ORDERDATE
FROM ORDERS
INNER JOIN PRODUCTS ON ORDERS.PRODUCTID = PRODUCTS.PRODUCTID